name: OtherworldlyOrnaments
author: PuckiSilver
version: v1.0.0
output: build
require:
  - bolt

data_pack:
  load:
    - libs/dp/*
    - src
  name: OtherworldlyOrnaments
  description: Find ornaments stemming from other worlds that provide you with unique buffs and allow you to travel to their dimension

resource_pack:
  load:
    # - libs/rp/*
    - src
  name: OtherworldlyOrnaments-RP
  description: Find ornaments stemming from other worlds that provide you with unique buffs and allow you to travel to their dimension

pipeline:
  - mecha
  - plugins.remove_empty_functions
  - plugins.credit
meta:
  credit: [psdpj11]
